# Generated by Django 5.0.7 on 2024-07-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_enrollment',
            field=models.IntegerField(null=True),
        ),
    ]
